#spring.application.name=restaurante
#
#
## Configurando o Banco H2 em Memoria
## salva na mememoria ---> spring.datasource.url=jdbc:h2:mem:restaurantebd
#spring.datasource.url=jdbc:h2:file:./data/restaurantebd;DB_CLOSE_ON_EXIT=FALSE
#
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## Configuracoes do console Web do H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## Configurando JPA/Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
spring.application.name=restaurante

# Configurando o Banco H2 Local em Arquivo (Criação automática liberada)
spring.datasource.url=jdbc:h2:file:./data/restaurantebd;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do console Web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurando JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true